'use client'

import { useState } from 'react'
import { addAdminException, deleteAdminException } from '@/app/actions/admin'

type Exception = { id: number; barberId: number; barber: string; date: string; startTime: string; endTime: string; description: string }
type Barber = { id: number; name: string; role: string }

export function AdminExceptions({ initial, barbers, onChanged }: { initial: Exception[]; barbers: Barber[]; onChanged: () => Promise<void> }) {
  const [items, setItems] = useState(initial)
  const [form, setForm] = useState({ barberId: String(barbers[0]?.id ?? ''), date: '', closed: true, startTime: '09:00', endTime: '18:00', description: '' })
  const [saving, setSaving] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { await addAdminException({ barberId: Number(form.barberId), date: form.date, startTime: form.closed ? undefined : form.startTime, endTime: form.closed ? undefined : form.endTime, description: form.description }); setForm({ ...form, date: '', description: '' }); await onChanged(); setItems([]) } finally { setSaving(false) } }
  return <section className="mt-8 rounded-sm border border-border bg-card p-5"><p className="text-xs uppercase tracking-[0.2em] text-primary">Exceções de disponibilidade</p><h2 className="mt-1 font-serif text-2xl uppercase">Feriados e horários especiais</h2><form onSubmit={submit} className="mt-5 grid gap-3 md:grid-cols-6"><select required value={form.barberId} onChange={e => setForm({ ...form, barberId: e.target.value })} className="min-h-11 rounded-sm border border-border bg-background px-3"><option value="">Barbeiro</option>{barbers.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><input required type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} className="min-h-11 rounded-sm border border-border bg-background px-3"/><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.closed} onChange={e => setForm({ ...form, closed: e.target.checked })}/> Fechado</label>{!form.closed && <><input required type="time" value={form.startTime} onChange={e => setForm({ ...form, startTime: e.target.value })} className="min-h-11 rounded-sm border border-border bg-background px-3"/><input required type="time" value={form.endTime} onChange={e => setForm({ ...form, endTime: e.target.value })} className="min-h-11 rounded-sm border border-border bg-background px-3"/></>}<input required placeholder="Descrição" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-11 rounded-sm border border-border bg-background px-3"/><button disabled={saving} className="min-h-11 rounded-full bg-primary px-4 text-primary-foreground">{saving ? 'A guardar…' : 'Adicionar'}</button></form><div className="mt-6 divide-y divide-border">{items.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><span><strong>{item.date}</strong> · {item.barber} · {item.startTime ? `${item.startTime}–${item.endTime}` : 'Fechado'} · {item.description}</span><button type="button" onClick={async () => { await deleteAdminException(item.id); await onChanged(); setItems(items.filter(x => x.id !== item.id)) }} className="text-destructive">Remover</button></div>)}</div></section>
}
